plex:
  image: wernight/plex-media-server:autoupdate
  ports:
    - "32400:32400"
  volumes:
    - ~/config/plex:/config
    - ~/media:/media
  net: "host"
  restart: always
plexpy:
  image: linuxserver/plexpy
  ports:
    - "8181:8181"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ~/config/plexpy:/config
    - ~/config/plex/Plex\ Media\ Server/Logs:/logs:ro
