plex:
  env_file: .env
  image: wernight/plex-media-server:autoupdate
  ports:
    - "32400:32400"
  volumes:
    - ~/config/plex:/config
    - ~/media:/media
  net: "host"
  restart: always

plexpy:
  env_file: .env
  image: linuxserver/plexpy
  ports:
    - "8181:8181"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ~/config/plexpy:/config
    - ~/config/plex/Plex\ Media\ Server/Logs:/logs:ro
  restart: always

sonarr:
  env_file: .env
  image: linuxserver/sonarr
  ports:
    - "8989:8989"
  volumes:
    - /dev/rtc:/dev/rtc:ro
    - ~/config/sonarr:/config
    - ~/downloads/sabnzbd/complete:/downloads
    - ~/config/couchpotato/blackhole:/blackhole
    - ~/media/tv:/tv
  restart: always

pydio:
  env_file: .env
  image: linuxserver/pydio
  ports:
    - "443:443"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ~/config/pydio:/config
    - ~/data/pydio:/data
    - /home:/host-home
  restart: always

requests:
  env_file: .env
  environment:
    - BRANCH=master
  image: aptalca/docker-plexrequests
  ports:
    - "3000:3000"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ~/config/requests:/config:rw
  restart: always

deluge:
  env_file: .env
  image: linuxserver/deluge
  net: host
  volumes:
    - ~/downloads/sabnzbd/complete:/downloads
    - ~/config/deluge:/config
    - /etc/localtime:/etc/localtime:ro
  restart: always

headphones:
  env_file: .env
  image: linuxserver/headphones
  ports:
    - "8282:8181"
  volumes:
    - ~/config/headphones:/config
    - ~/downloads/sabnzbd/complete:/downloads
    - ~/media/music:/music
    - /etc/localtime:/etc/localtime:ro
  restart: always

couchpotato:
  env_file: .env
  image: linuxserver/couchpotato
  ports:
    - "5050:5050"
  volumes:
    - ~/config/couchpotato:/config
    - ~/downloads/sabnzbd/complete:/downloads
    - ~/media/movies:/movies
    - /etc/localtime:/etc/localtime:ro
  restart: always

sabnzbd:
  env_file: .env
  image: needo/sabnzbd
  ports:
    - "8088:8080"
    - "9099:9090"
  volumes:
    - ~/config/sabnzbd:/config
    - ~/downloads/sabnzbd/complete:/downloads
    - ~/downloads/sabnzbd/incomplete:/incomplete-downloads
    - /etc/localtime:/etc/localtime:ro
  restart: always
