plex:
  env_file: .env
  image: wernight/plex-media-server:autoupdate
  ports:
    - "32400:32400"
  volumes:
    - ~/config/plex:/config
    - ~/media:/media
  net: "host"
  restart: always
plexpy:
  env_file: .env
  image: linuxserver/plexpy
  ports:
    - "8181:8181"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ~/config/plexpy:/config
    - ~/config/plex/Plex\ Media\ Server/Logs:/logs:ro
sonarr:
  env_file: .env
  image: linuxserver/sonarr
  ports:
    - "8989:8989"
  volumes:
    - /dev/rtc:/dev/rtc:ro
    - ~/config/sonarr:/config
    - ~/downloads/sabnzbd/complete:/downloads
    - ~/config/couchpotato/blackhole:/blackhole
    - ~/media/tv:/tv
pydio:
  env_file: .env
  image: linuxserver/pydio
  ports:
    - "443:443"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ~/config/pydio:/config
    - ~/data/pydio:/data
    - /home:/host-home
requests:
  env_file: .env
  environment:
    - BRANCH=master
  image: aptalca/docker-plexrequests
  ports:
    - "3000:3000"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ~/config/requests:/config:rw
deluge:
  env_file: .env
  image: linuxserver/deluge
  net: host
  volumes:
    - ~/downloads/sabnzbd/complete:/downloads
    - ~/config/deluge:/config
    - /etc/localtime:/etc/localtime:ro
